# Generated by Django 4.0.4 on 2022-05-17 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='images',
        ),
    ]
