# Generated by Django 4.0.4 on 2022-05-18 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password'),
        ('postings', '0003_posting_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posting',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='posting',
            new_name='post',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
