# Generated by Django 4.0.4 on 2022-05-19 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_rename_posting_post_rename_posting_image_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contents',
            new_name='content',
        ),
    ]
