# Generated by Django 4.0.4 on 2022-05-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_accounts_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
