# Generated by Django 4.0.4 on 2022-05-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_followfollwing_followfollowing_and_more'),
        ('postings', '0003_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='users.user'),
        ),
        migrations.AlterField(
            model_name='like',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting', to='postings.posting'),
        ),
    ]
