# Generated by Django 4.0.4 on 2022-05-20 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowFollwing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'followsfollwings',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='followfollwing',
            field=models.ManyToManyField(through='users.FollowFollwing', to='users.user'),
        ),
        migrations.AddField(
            model_name='followfollwing',
            name='follow_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to='users.user'),
        ),
        migrations.AddField(
            model_name='followfollwing',
            name='following_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to='users.user'),
        ),
    ]
