# Generated by Django 4.0.4 on 2022-05-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_followfollwing_user_followfollwing_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowFollwing',
            new_name='FollowFollowing',
        ),
        migrations.AlterModelTable(
            name='followfollowing',
            table='followsfollowings',
        ),
    ]
